name: sigmetrics-tool
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - bcrypt=3.2.0=py39he8ac12f_0
  - blas=1.0=mkl
  - bottleneck=1.3.2=py39hdd57654_1
  - brotlipy=0.7.0=py39h27cfd23_1003
  - ca-certificates=2021.9.30=h06a4308_1
  - certifi=2021.10.8=py39h06a4308_0
  - cffi=1.14.6=py39h400218f_0
  - chardet=4.0.0=py39h06a4308_1003
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cryptography=3.4.8=py39hd23ed53_0
  - idna=3.2=pyhd3eb1b0_0
  - intel-openmp=2021.3.0=h06a4308_3350
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libgomp=9.3.0=h5101ec6_17
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - mkl=2021.3.0=h06a4308_520
  - mkl-service=2.4.0=py39h7f8727e_0
  - mkl_fft=1.3.0=py39h42c9631_2
  - mkl_random=1.2.2=py39h51133e4_0
  - ncurses=6.2=he6710b0_1
  - numexpr=2.7.3=py39h22e1b3c_1
  - numpy=1.20.3=py39hf144106_0
  - numpy-base=1.20.3=py39h74d4b33_0
  - openssl=1.1.1l=h7f8727e_0
  - pandas=1.3.3=py39h8c16a72_0
  - paramiko=2.7.2=py_0
  - pip=21.2.4=py39h06a4308_0
  - pycparser=2.20=py_2
  - pynacl=1.4.0=py39he8ac12f_1
  - pyopenssl=20.0.1=pyhd3eb1b0_1
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.7=h12debd9_1
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - pytz=2021.3=pyhd3eb1b0_0
  - readline=8.1=h27cfd23_0
  - requests=2.26.0=pyhd3eb1b0_0
  - scipy=1.7.1=py39h292c36d_2
  - scp=0.13.6=pyhd3eb1b0_0
  - setuptools=58.0.4=py39h06a4308_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.36.0=hc218d9a_0
  - tk=8.6.11=h1ccaba5_0
  - tzdata=2021a=h5d7bf9c_0
  - urllib3=1.26.7=pyhd3eb1b0_0
  - wheel=0.37.0=pyhd3eb1b0_1
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - geni-lib==0.9.9.4
    - ipaddress==1.0.23
    - lxml==4.6.3
    - wrapt==1.13.1
